<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>CNCMaps.GUI</RootNamespace>
    <AssemblyName>CNCMaps.Renderer.GUI</AssemblyName>
    <ApplicationIcon>ra2mapicon.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="5.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CNCMaps.Engine\CNCMaps.Engine.csproj" />
    <ProjectReference Include="..\CNCMaps.FileFormats\CNCMaps.FileFormats.csproj" />
    <ProjectReference Include="..\CNCMaps.Shared\CNCMaps.Shared.csproj" />
  </ItemGroup>
</Project>
