<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CNCMaps</RootNamespace>
    <AssemblyName>CNCMaps.Renderer</AssemblyName>
    <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="5.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CNCMaps.Engine\CNCMaps.Engine.csproj" />
    <ProjectReference Include="..\CNCMaps.Shared\CNCMaps.Shared.csproj" />
  </ItemGroup>
</Project>
