<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CNCMaps.Engine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="5.5.0" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CNCMaps.FileFormats\CNCMaps.FileFormats.csproj" />
    <ProjectReference Include="..\CNCMaps.Shared\CNCMaps.Shared.csproj" />
  </ItemGroup>
</Project>
